FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY install.sh /usr/share/nginx/html/install.sh
COPY install.ps1 /usr/share/nginx/html/install.ps1
COPY dashboard.html /usr/share/nginx/html/dashboard.html
EXPOSE 80
